--#SET TERMINATOR @
CREATE PROCEDURE
  UPDATE_LEADERS_SCORE (IN IN_SCHOOL_ID INTEGER, IN IN_LEADER_SCORE INTEGER)
  P1: BEGIN

  --  ######################################################################
  --  # Returns count of tables created by  and like VARNAME
  --  ######################################################################

UPDATE CHICAGO_PUBLIC_SCHOOLS SET LEADERS_SCORE = IN_LEADER_SCORE WHERE SCHOOL_ID = IN_SCHOOL_ID;

IF IN_LEADER_SCORE < 20 THEN UPDATE CHICAGO_PUBLIC_SCHOOLS SET LEADERS_ICON = 'VERY WEAK' WHERE SCHOOL_ID = IN_SCHOOL_ID;
ELSEIF IN_LEADER_SCORE < 40 THEN UPDATE CHICAGO_PUBLIC_SCHOOLS SET LEADERS_ICON = 'WEAK' WHERE SCHOOL_ID = IN_SCHOOL_ID;
ELSEIF IN_LEADER_SCORE < 60 THEN UPDATE CHICAGO_PUBLIC_SCHOOLS SET LEADERS_ICON = 'AVERAGE' WHERE SCHOOL_ID = IN_SCHOOL_ID;
ELSEIF IN_LEADER_SCORE < 80 THEN UPDATE CHICAGO_PUBLIC_SCHOOLS SET LEADERS_ICON = 'STRONG' WHERE SCHOOL_ID = IN_SCHOOL_ID;
ELSEIF (IN_LEADER_SCORE > 80 AND IN_LEADER_SCORE < 101) THEN UPDATE CHICAGO_PUBLIC_SCHOOLS SET LEADERS_ICON = 'VERY STRONG' WHERE SCHOOL_ID = IN_SCHOOL_ID;
ELSEIF IN_LEADER_SCORE > 100 THEN ROLLBACK WORK;
END IF;

COMMIT WORK;

END P1@ --#SET TERMINATOR ;
